name: new_minicab_driver
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.0
  dropdown_button2: 2.3.9
  firebase_core: ^3.0.0
  firebase_auth: ^5.3.0
  flutter_overlay_window: ^0.4.5
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: ^6.2.1
  intl: 0.19.0
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  pin_code_fields: 8.0.1
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  sign_in_with_apple: ^6.1.3
  sqflite: 2.4.0
  timeago: 3.2.2
  url_launcher: 6.3.1
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0
  google_maps: 8.0.0
  google_maps_flutter: ^2.9.0
  intl_phone_field: ^3.2.0
  geolocator: ^13.0.2
  latlong2: ^0.9.0
  fluttertoast: ^8.2.10
  image_picker: ^1.1.2
  flutter_blurhash: ^0.8.2
  fl_location: ^3.0.0
  http: ^1.2.1
  pdf: ^3.10.7
  open_file: ^3.5.5
  flutter_tts: ^3.7.0
  flutter_datetime_picker: ^1.5.1
  toggle_switch: ^2.1.0
  flutter_swipe_button: ^2.1.3
  glowy_borders: ^1.0.2
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^2.0.1
  flutter_local_notifications: ^17.1.0
  flutter_background_service: ^5.1.0
  stop_watch_timer: ^3.1.1
  pusher_client_fixed: ^0.0.5
  get: ^4.6.6
  audioplayers: ^6.0.0
  flutter_widget_from_html_core: ^0.15.2
  location: ^7.0.1
  dio: ^5.8.0+1

dependency_overrides:
  image_picker_android: ^0.8.12+15
  shared_preferences_android: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/pngwing.com.png
    - assets/videos/
    - assets/audios/
    - assets/audios/beep.mp3
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
