name: mini_cab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
# environment:
#   sdk: ">=3.0.0 <4.0.0"
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.0
  dropdown_button2: 2.3.9
  firebase_auth: ^4.6.2
  firebase_auth_platform_interface: 6.15.2
  firebase_auth_web: 5.5.2
  firebase_core: 2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: 2.5.0
  firebase_performance: 0.9.2+2
  firebase_performance_platform_interface: 0.1.4+2
  firebase_performance_web: 0.1.4+2
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  intl: 0.19.0
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  # path_provider_android: 2.0.25
  # path_provider_foundation: 2.3.2
  # path_provider_platform_interface: 2.1.0
  pin_code_fields: 8.0.1
  # plugin_platform_interface: 2.1.6
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  flutter_polyline_points: ^1.0.0
  google_maps: 6.3.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.1
  google_maps_flutter_web: ^0.5.4+2
  intl_phone_field: ^3.2.0
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  google_distance_matrix: ^0.0.1
  firebase_app_check: ^0.1.4+2
  fluttertoast: ^8.2.4
  image_picker: ^0.8.3+1
  image_picker_for_web: ^2.1.0
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: ^2.0.0
  flutter_blurhash: ^0.8.2
  fl_location: ^3.0.0
  google_maps_webservice: ^0.0.19
  http: ^0.13.5
  google_directions_api: ^0.9.1
  pdf: ^3.10.7
  open_file: ^3.3.2
#  location: ^5.0.3
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.0
  google_maps_routes: ^1.1.2
  toggle_switch: ^2.1.0
  flutter_swipe_button: ^2.1.3
  glowy_borders: ^1.0.2
  # flutter_ringtone_player: ^3.2.0
  flutter_ringtone_player: ^4.0.0
  vibration: ^1.8.4
  flutter_local_notifications: ^17.1.2
  flutter_background_service: ^5.0.5
  root_checker_plus: ^0.0.3
  system_alert_window: ^2.0.0
  stop_watch_timer: ^3.1.1
  pusher_client_fixed: ^0.0.4+1
  get: ^4.6.6



dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'



flutter:



  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/pngwing.com.png
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
      
     
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
